extra_javascript:
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega@6
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-lite@6
  - https://cdn.jsdelivr.net/npm/vega-embed@6
  - https://cdn.jsdelivr.net/npm/vega-embed@7
site_name: Enkiria Wiki
site_url: https://zamer12.github.io/Enkiria-Wiki
theme:
  name: material
  font:
    text: Acme
    code: JetBrains Mono
  icon:
    logo: material/pokeball
  favicon: assets/favicon.ico
  palette:
    # Darkmode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark Mode
      primary: deep purple
      accent: purple
    # Lightmode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light Mode
      primary: deep purple
      accent: purple
  features:
    - navigation.tabs
    - navigation.top
    - navigation.expand
    - navigation.sections
    - navigation.footer
    - social.cards
  social:
    image: "assets/socials/water-gym-social.jpg"  # Image par défaut pour les cartes sociales

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
       custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: vegalite
          class: vegalite
          format: !!python/name:mkdocs_charts_plugin.fences.fence_vegalite
  - admonition
  - pymdownx.details
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - md_in_html
  - pymdownx.blocks.caption
  - meta
  - tables

plugins:
  - glightbox
  - search
  - charts
  - table-reader
  - autolinks 
  - social
  - meta
  - mkdocs-audio
 
extra_css: 
  - styles/figure.css
  - styles/Imgs.css
  - stylesheets/calendar.css
  
copyright: Wiki by ZaMeR12, 2026

extra:
  social:
    - icon: material/github
      link: https://github.com/ZaMeR12/Enkiria-Wiki
    - icon: simple/discord
      link: https://discord.gg/RUjgy7wKXr